# For more information: https://laravel.com/docs/sail
version: '3'
services:
    node:
        image: node:19-alpine
        working_dir: '/app'
        command:
            - sh
            - -c
            - |
                npm i
                npm run dev
        ports:
            - '5173:5173'
        volumes:
            - '.:/app'
        depends_on:
            - mysql
    php:
        build: .
        working_dir: '/app'
        command:
            -   bash
            -   -c
            -   |
                composer install
                rm ./public/storage
                php artisan storage:link
                php artisan migrate
                php artisan serve --host 0.0.0.0:8000
        ports:
            -   '8000:8000'
        volumes:
            -   '.:/app'
        depends_on:
            -   mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: laravel
            MYSQL_USER: admin
            MYSQL_PASSWORD: root
        volumes:
            - './mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-proot"]
            retries: 3
            timeout: 5s
