version: "3.9"
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  apache:
    build: .
    restart: always
    volumes:
      - '.:/var/www/html/'
    ports:
      - 80:80
